### ISSUE TITLE
Build errors on node@8 due to outdated Gulp-Sass 

### ISSUE THREAD

**Issue by yuletide** [liorgrossman/darkness#73]
Just did an update and now getting build errors. Looks like an old issue of https://github.com/sass/node-sass is the culprit.

```
Node/darkness(master) ☸ npm install

> Darkness@1.0.0 install /Users/ay/code/darkness
> gulp install

/Users/ay/code/darkness/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/Users/ay/code/darkness/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/ay/code/darkness/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ay/code/darkness/node_modules/gulp-sass/index.js:187:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Darkness@1.0.0 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Darkness@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

From https://github.com/sass/node-sass/releases/tag/v3.13.1, node v7 is the latest supported version. Looks like an old version of `gulp-sass` is the issue. Bumping to 4.0.0 fixed it (see #74)

**Comment by liorgrossman** [comment]
Thank you for the fix Alex, merged into master!
